name: Pre-commit Checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install pre-commit
        run: pip install pre-commit

      - name: Cache pre-commit hooks
        uses: actions/cache@v3
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}

      - name: Setup OpenTofu
        uses: opentofu/setup-opentofu@v1
        with:
          tofu_version: latest
          tofu_wrapper: false

      - name: Install terraform-docs
        run: |
          curl -sSLo ./terraform-docs.tar.gz https://terraform-docs.io/dl/v0.16.0/terraform-docs-v0.16.0-$(uname)-amd64.tar.gz
          tar -xzf terraform-docs.tar.gz
          chmod +x terraform-docs
          sudo mv terraform-docs /usr/local/bin/
          terraform-docs --version

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Cache act tool
        uses: actions/cache@v3
        id: cache-act
        with:
          path: ~/.cache/act
          key: act-${{ runner.os }}-${{ hashFiles('scripts/test-github-workflows.sh') }}

      - name: Install act
        if: steps.cache-act.outputs.cache-hit != 'true'
        run: |
          mkdir -p ~/.cache/act
          curl -s https://raw.githubusercontent.com/nektos/act/master/install.sh | bash -s -- -b ~/.cache/act
          echo "~/.cache/act" >> $GITHUB_PATH

      - name: Add act to PATH
        run: echo "~/.cache/act" >> $GITHUB_PATH

      - name: Run pre-commit
        run: pre-commit run -a
