exclude: '^dist$'
fail_fast: false
# .pre-commit-config.yaml
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: '.*dist\/.*|package-lock.json'
      - id: check-yaml
      - id: check-json
      - id: check-merge-conflict
      - id: check-added-large-files

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        stages: [commit]

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v10.2.0
    hooks:
      - id: eslint
        args: [ --no-warn-ignored, --fix ]
        files: \.[jt]sx?$  # match JavaScript and TypeScript files
        exclude: '.*dist\/.*'
        types: [ file ]
        additional_dependencies:
          - eslint
          - '@eslint/js'
